### ISSUE TITLE
Context URL resolves to 404

### ISSUE THREAD

**Issue by nikosft** [w3c/vc-status-list-2021#21]
This is the same as #10 which shouldn't be closed. The provided examples use https://w3id.org/vc-status-list-2021/v1 as context URL, which resolves to 404.

**Comment by marek5050** [comment]
Maybe this? https://w3c-ccg.github.io/vc-status-list-2021/contexts/v1.jsonld

**Comment by rolsonquadras** [comment]
@msporny The context from the example is giving 404 - https://w3id.org/vc/status-list/2021/v1. This URL redirects to https://w3c-ccg.github.io/vc-status-list-2021/contexts/v1.jsonld. Probably the redirection needs to be updated to the context file in the new GitHub repo - https://w3c.github.io/vc-status-list-2021/contexts/v1.jsonld.

**Comment by msporny** [comment]
Fixed in https://github.com/perma-id/w3id.org/commit/86990ae6bd3d7e2abe3076d42e60689ce45f8672
