### ISSUE TITLE
Hexstrings vs. Bitstrings

### ISSUE THREAD

**Issue by kezike** [w3c/vc-status-list-2021#5]
Somewhat related to the idea of multiple topics broached in #2: have we considered using hexstrings (instead of bitstrings) to capture multiple states per credential or is that an entirely new spec with much more complexity?

The main benefit with this approach is that we could capture multiple states for each credential directly in the list string data structure. One issue I can think of is that it requires a larger uncompressed string to represent the same number of credentials, which may be alright depending on how we design the credential states and the frequency of encountering truthy values in said design. Another issue is that we would have to define all possible statuses in a table, but at least there is modern precedence for this design pattern in the [multibase](https://github.com/multiformats/multibase) and [multicodec](https://github.com/multiformats/multicodec) work out of [Protocol Labs](https://protocol.ai).

Inviting discussion on more pros and cons in this thread as well as general feedback on this approach 👀

**Comment by msporny** [comment]
> Somewhat related to the idea of multiple topics broached in #2: have we considered using hexstrings (instead of bitstrings) to capture multiple states per credential or is that an entirely new spec with much more complexity?

It's an interesting idea. The current approach is a separate bitstring list per status type. The problem w/ hexstrings is that you end up presuming 16 values per VC (perhaps?) and so you're going to end up with wasted space (maybe) vs. just one property per bitstring.

Feels like multi-state encodings would be an entirely different spec. Just my $0.02.

**Comment by OR13** [comment]
Suggest closing

**Comment by msporny** [comment]
Multi-bit bitstrings are now supported in the spec, closing.
