### ISSUE TITLE
Need examples for how to handle multiple status messages

### ISSUE THREAD

**Issue by mprorock** [w3c/vc-status-list-2021#66]
see pr #65 - need to add an example section

**Comment by mprorock** [comment]
a minimal example of how to set status messages with the way things are written now:

```
"message": [
  {"status":"0x00", "value":"valid"},
  {"status":"0x01", "value":"invalid"},
  {"status":"0x02", "value":"hold"},
  ...
]
```

but this could obviously be extended with hints around whether to verify a credential (if that were appropriate for the use case - not all statuses are related to whether or not to verify a credential):

```
"message": [
  {"status":"0x00", "value":"valid", "verify": true},
  {"status":"0x01", "value":"invalid", "verify": false},
  {"status":"0x02", "value":"hold", "verify": true},
  ...
]
```

**Comment by OR13** [comment]
See also https://github.com/w3c-ccg/vc-api/issues/225
